language: cpp

matrix:
  include:
  - os: osx
    name: "Build"
    osx_image: xcode10.2
    compiler: clang

    script:
      - xcodebuild -configuration Debug
      - xcodebuild -configuration Release

    deploy:
      provider: releases
      skip_cleanup: true
      file: "build/*/*/*.zip"
      file_glob: true
      api_key:
        secure: zrg0O6fDo1iXr86prTlPSkhmyxPzIqxHRsHi97442D1Ndd8WIAbxMAWnEKCvd9AZOkGg/quoI9svUkiKcCZw2sFdgCweM6bLevFXkX1KoKDOdQWu3f0I1DJeffF1NQAmQgGWchCOMUqDFvgwKNGVe4peSWeR33r7jySbmO7pGCxplee5UQl2PDZyV4WS+OBlKFRao95OVOQ86Bahtxu7PVKPdwbK78V07ZncI5OeffQkHSklfYaMDwTYBDmVq73hvC3Zkhugs6or6t2f1WvCpJVO+uP3W2rz8gKEEaycu4Ig/hPqiCFgtJvNyhE47Go6ZZO8/P04nzoowBQ+QgXZV5bwBUocGGYU5L/BspkqCRQTeIT1t4WvVK8oRM9IBXffjun+E0kx+HF0h1kz5S/pihrDRcebqHvm7tbSeCJ7A+1l+5sUNuwuCeMKgT0MhnjGML663eh3lTObSdP051NWsuBqvJGf0zllxtqQiXKoHiTGC93G/5YKIMvpBktGzxxwY7aPvRciEmR+nu7zojYfSjK/rVfZ/2tmFr40UUNtVVY9zou/ixMx4MescwZjA+/Aa1aLURKNhPPJYIDJhOhHLF2zPDwt9QamtxsdjOFs9qLi6MEEv0qCFLwweaKLF3HAJvnJatAfC040xbDGd3epOj0y/AQJJiZC968HMg3qupQ=
      on:
        tags: true

  - os: osx
    name: "Analyze Clang"
    osx_image: xcode11
    compiler: clang

    script:
      - xcodebuild analyze -quiet -scheme BrcmPathRAM -configuration Debug CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang-analyze" && [ "$(find clang-analyze -name "*.html")" = "" ]
      - xcodebuild analyze -quiet -scheme BrcmPathRAM -configuration Release CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang-analyze" && [ "$(find clang-analyze -name "*.html")" = "" ]
